#+TITLE: Typst Mode

An Emacs major mode for [[https://typst.app/][typst]], a markup-based typesetting system.

* Requirements
external executable: [[https://github.com/typst/typst][typst]]

Emacs package: [[https://github.com/polymode/polymode][polymode]] (if you use =straight=, it will automatically download this requirement for you)

Minimum Emacs version hasn't been tested

* Installation
** Use-package and straight
#+begin_src emacs-lisp
(use-package typst-mode
  :straight (:type git :host github :repo "Ziqi-Yang/typst-mode.el"))
#+end_src

** Manually
#+begin_src emacs-lisp
;; push typst-mode directory to the load-path like this
(push (expand-file-name "modules/languages/typst-mode" user-emacs-directory) load-path)
;; load tyspt-mode
(require 'typst-mode)
#+end_src

** Other Methods
For instance, Emacs' builtin =pakcage.el=. \\
If you use other methods to load =typst-mode=, please consider creating a pull-request by simply clicking on the =edit= icon located in the top-right region of this README file.

* Current Features
** Functions
1. =typst-compile=  (default bind: =C-c C-c=)
2. =typst-preview= (default bind: =C-c C-p=)
3. =typst-toggle-watch= (default bind: =C-c C-w=; also provide =typst-watch= and =typst-stop-watch=)
** Style
*** Markup
| feature          | support | Example              |
|------------------+---------+----------------------|
| Paragraph break  | ✓       |                      |
| Strong emphasis  | ✓       | *strong*               |
| Emphasis         | ✓       | /emphasis/             |
| Raw text         | inline  | `print(1)`           |
| Link             | ✓       | https://typst.app/   |
| Label            | ✓       | <intro>              |
| Reference        | ✓       | @intro               |
| Heading          | ✓       | == Heading=            |
| Bullet list      | ✓       | - item               |
| Numbered list    | ✓       | + item               |
| Term list        | ✓       | / Term: description  |
| Math             |         | =$x^2$=                |
| Line break       | ✓       | \                    |
| Smart quote      |         | 'single' or "double" |
| Symbol shorthand |         | ~, ---               |
| Code expression  | name    | =#rect(width: 1cm)=    |
| Character escape | ✓       | Tweet at us \#ad     |
| Comment          | ✓       | =/* block */, // line= |

* Customization
faces and custom variables with prefix =typst= or =typst-mode=

* To Dos
1. [ ] fix math mode 
2. [ ] add treesit mode
3. [ ] show compile errors at real time when in Typst =watch= mode

* Current Shortages
For those stuffs cannot be done in short future.
1. no syntax support for the context block =[ ]= which is located in the code block ={ }= \\
   this problem possibly can be solved with *nested polymode*. However, currently there is no official support for this function?
2. indentation in code mode(contents between '{' and '}') may not works well, like this: \\
   (hitting `tab` to indent has problem, but it works well when directly call `typst-indent-line`)
   
   #+begin_src plain
   begin_code {
   [ // no indentation on this line.
    [ // indentation works well
    ]
   ]
   }
   #+end_src
   The issue may caused by Polymode. I have created an issue here: [[https://github.com/polymode/polymode/issues/328][https://github.com/polymode/polymode/issues/328]]

   *Temporary solution*: \\
Manually execute the =typst-indent-line= command on the first line of the code block. Then the following indentations will work properly.   
