#+TITLE: Typst Mode

An Emacs major mode for [[https://typst.app/][typst]], a markup-based typesetting system.

Since the language style of =typst= is somewhat complicated to parse(at least for me), currently this package  only provides limited syntax highlighting feature :( Maybe complicated cases should be implemented into lsp server?

* Requirements
[[https://github.com/typst/typst][typst]]

[[https://github.com/polymode/polymode][polymode]]

minium Emacs version hasn't been tested

* Current Features
** Functions
1. =typst-compile=  (default bind: =C-c C-c=)
2. =typst-preview= (default bind: =C-c C-p=)
3. =typst-toggle-watch= (default bind: =C-c C-w=; also provide =typst-watch= and =typst-stop-watch=)
** Style
*** Markup
| feature          | support | Example              |
|------------------+---------+----------------------|
| Paragraph break  | ✓       |                      |
| Strong emphasis  | ✓       | *strong*               |
| Emphasis         | ✓       | /emphasis/             |
| Raw text         | inline  | `print(1)`           |
| Link             | ✓       | https://typst.app/   |
| Label            | ✓       | <intro>              |
| Reference        | ✓       | @intro               |
| Heading          | ✓       | == Heading=            |
| Bullet list      | ✓       | - item               |
| Numbered list    | ✓       | + item               |
| Term list        | ✓       | / Term: description  |
| Math             |         | =$x^2$=                |
| Line break       | ✓       | \                    |
| Smart quote      |         | 'single' or "double" |
| Symbol shorthand |         | ~, ---               |
| Code expression  | name    | =#rect(width: 1cm)=    |
| Character escape | ✓       | Tweet at us \#ad     |
| Comment          | ✓       | =/* block */, // line= |

* Customization
faces and custom variables with prefix =typst= or =typst-mode=

* To Dos
1. [ ] fix math mode 
2. [ ] code block highlight
3. [ ] add treesit mode

* Current Shortages
For those stuffs cannot be done in short future.
1. no syntax support for the context block =[ ]= which is located in the code block ={ }= \\
   this problem possibly can be solved with *nested polymode*. However, currently there is no official support for this function?
2. indentation in code mode(contents between '{' and '}') may not works well, like this: \\
   (hitting `tab` to indent has problem, but it works well when directly call `typst-indent-line`)
   
   #+begin_src plain
   begin_code {
   [ // no indentation on this line.
    [ // indentation works well
    ]
   ]
   }
   #+end_src
   The issue may caused by Polymode. I have created an issue here: [[https://github.com/polymode/polymode/issues/328][https://github.com/polymode/polymode/issues/328]]
   
*This is my first Emacs lisp package and I greatly value your assistance, including issues, pull requests, and more!*
